site:
  # set the domain with schema but without trailing slash:
  domain: 'https://gitsite.org'
  root-path: /Learning2Peak
  title: Learning2Peak
  description: Learning2Peak is a static web site generator for Git.
  keywords: learning2peak, git, static web site, html
  theme: default
  language: en-US
  # set the /<rootPath> pathname under which your site is served
  # for GitHub pages deployment without a custom domain, it is often '/<projectName>'
  # root-path: /gitsite
  # set cdn path:
  cdn-path: https://cdn.jsdelivr.net/npm
  navigation:
    - title: AI Coding Guide
      uri: /books/AI-coding/index.html
    - title: Cyber Tracking
      uri: /books/Cyber-Tracking/index.html
    - title: SeekingComfortZone
      uri: /books/SeekingComfortZone/index.html
    - title: Smart Collection
      uri: /books/Smart-Collection/index.html
    - title: Blogs
      uri: /blogs/tech/index.html
    - title: License
      uri: /pages/license/index.html
  git:
    base-url: https://github.com/Orangon/Learning2Peak/blob/main/source
  contact:
    name: Orangon
    github: https://github.com/Orangon
    twitter: https://twitter.com/oooooooooooo
  books:
    index-marker: true
  search:
    # none = no search
    # browser = flex search in browser
    # google = google site search
    type: browser
  # control styles:
  styles:
    # show 'Edit in Git':
    display-git-link: true
    # any custom styles used in theme:
    # code-font: Monaco
  integration:
    comment:
      provider: disqus
      name: gitsite
    analytics:
      provider: google
      gtag: G-5Z40K7NBL5

build:
  # copy special files under root dir (ignore if not found):
  copy:
    - favicon.ico
    - robots.txt
    - ads.txt

# you can add any items:
